### ISSUE TITLE
Hi update 

### ISSUE THREAD

**Issue by NoRRt** [DJScias/WowheadParser#1]
Hi update last  patch 8.3.0

**Comment by DJScias** [comment]
Hello there,

What's different from how 8.0.1 and 8.3 handle the generated SQLs?

**Comment by Thordekk** [comment]
whats about shadowlands

**Comment by zabiksandbox** [comment]
WH change dom for loot and some js variables like LANG.drops -> WH.TERMS.drops. Tool need update.

**Comment by DJScias** [comment]
Latest update of the tool should work with current wowhead style again + added 9.2.0 (latest TC).
